server:
    port: 4001
    tomcat:
        uri-encoding: utf-8
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ybl?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            idle-timeout: 60000
            minimum-idle: 10
            maximum-pool-size: 10
            pool-name: DatebookHikariCP
            max-lifetime: 180000
            connection-timeout: 60000
            login-timeout: 5
            validation-timeout: 3000
    jpa:
        show-sql: true
        database: mysql
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        com.townmc: debug
        com.zaxxer.hikari: debug